### PR TITLE
Aug20 Release

### PR DESCRIPTION
**Pull request by XiaoningLiu**

### CODE REVIEW

**Comment by XiaoningLiu** [comment]
@katmsft Please help review. Specifcily, refer to https://github.com/Azure/azure-storage-php/pull/250/commits/a92525761fd5e47b8e3639a8b4fe094dab35845f for my commit. Other commits in this PR are from customers.

**Comment by XiaoningLiu** [comment]
CI: https://dev.azure.com/azure/azure-storage-php/_build/results?buildId=13531&view=logs&j=5d071e35-3a5c-5e89-89e0-b30172c20704

**Review by katmsft — APPROVED** [review]
LGTM

**Pull request merged**
