### PR TITLE
Allow both guzzle 6.x and 7.x

### PR DESCRIPTION
**Pull request by Fanmade**
@see https://github.com/Azure/azure-storage-php/pull/255/commits

### CODE REVIEW

**Comment by XiaoningLiu** [comment]
Duplicated with #255 . Anyway looks good.

**Comment by Oxicode** [comment]
@XiaoningLiu  anything news? Please merge

**Review by XiaoningLiu — APPROVED** [review]

**Comment by chris-rs** [comment]
Great this has been merged. Please create a release with the guzzle update to fix dependencies.

**Comment by katmsft** [comment]
Duplicated.

**Pull request closed without merging**
