### PR TITLE
Allow both guzzle 6.x and 7.x

### LINKED ISSUE #248: Update "azure-storage-common" guzzle 6.0 dependency
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the SDK was used?
1.5.0

### What's the PHP/OS version?
PHP 7.3

### What problem was encountered?
"azure-storage-blob package" depends on "azure-storage-common" which depend on guzzle 6.0. This prevent updating/installing all other php packages that depend on guzzle 7x

### Steps to reproduce the issue?
try to install this package when guzzle 7.x installed

### Have you found a mitigation/solution?
No

### What is the storage account name and time frame of your last reproduce? (UTC YYYY/MM/DD hh:mm:ss)

(If you think some of the information should not be shared publicly, you can e-mail the main Microsoft contributors of the repository instead.)

### LINKED ISSUE #253: Open for use of v7.X of guzzlehttp/guzzle
better to support guzzle v7.x on storage-common-php 
because it will not work on laravel 8.

by default laravel 8 need guzzle ^v7.x

so please support latest version of guzzle.

already issue there ..https://github.com/Azure/azure-storage-common-php/issues/2

### PR DESCRIPTION
**Pull request by sadika9**
fixes #248
fixes #253

### CODE REVIEW

**Comment by Synalek** [comment]
@sadika9 @XiaoningLiu @katmsft One approval separates us from solving all issues 😄

**Review by Fanmade — APPROVED** [review]
We need this asap, seeing no issue or any breaking changes here

**Comment by andrei-dascalu** [comment]
Also looking forward to this

**Review by XiaoningLiu — APPROVED** [review]
Thanks for the contribution! Gernally looks good, start CI.

**Comment by XiaoningLiu** [comment]
To be included into next Nov. release.

**Comment by rdgout** [comment]
When is this going to be merged? It's been november for some time 😄

**Comment by helders** [comment]
Merge time!

**Comment by MrThePlague** [comment]
@XiaoningLiu Not to be a pest, but is there any chance this is going to be merged within the next few days? There are a number of projects which require this fix in order to support Laravel 8+.

**Comment by patrickatkeylogic** [comment]
I might be totally missing something but it's still not working for me. 

I'm not sure if this is causing my issues but the release repo for azure-storage-common-php is still stuck at guzzle 6.0: https://github.com/Azure/azure-storage-common-php/blob/master/composer.json

guzzle

This is a fresh installation of Laravel 8. I can provide more details if they are needed.

**Comment by WouterSioen** [comment]
This change is merged into the master branch but not released yet, so that's why it's not working yet. Waiting for a release!

**Comment by bnock** [comment]
Seriously?! I've been waiting for over a month for this simple update to be released so I can upgrade to Laravel 8.  I see above that I'm not the only one.  What's the hold up?  Release this already!!!  Sadly, this is what I've come to expect of Microsoft...

**Comment by hmazter** [comment]
@bnock FYI you don't need to update to Guzzle 7 to upgrade to Laravel 8. Laravel 8 works with both Guzzle 6 and 7
From the composer.json for `laravel/framework`
```
guzzlehttp/guzzle: ^6.5.5|^7.0.1
```

**Comment by bnock** [comment]
@hmazter thanks for pointing this out.  My issue was trying to follow the Laravel upgrade guide which explicitly says to update your project's composer.json requirement to guzzlehttp/guzzle: ^7.0.1.  So, someone like myself just trying to follow the guide AND use this library would run into issues.  

That being said, this fix was supposed to go out in November and now we're almost halfway through December so I still question: what's the hold up?

**Pull request merged**
