### PR TITLE
Include a link to the microsoft/azure-storage package

### PR DESCRIPTION
**Pull request by sergey-shandar**

### CODE REVIEW

**Comment by katmsft** [comment]
Thanks for the PR, LGTM.

**Comment by katmsft** [comment]
@sergey-shandar Please resolve the comments and re-send the PR.

**Comment by sergey-shandar** [comment]
@katmsft I've changed the base branch to Azure:dev.

**Comment by katmsft** [comment]
LGTM, @hasonmsft Please also take a look. Thanks.

**Pull request merged**
