### PR TITLE
Fix generateCanonicalResource substr

### PR DESCRIPTION
**Pull request by wslaghekke**
Adds missing $resource parameter to substr to fix generateCanonicalResource returning an empty string if $resource starts with /

### CODE REVIEW

**Comment by XiaoningLiu** [comment]
@wslaghekke Thanks for contribution. Sounds good! Under validation will update later.

**Comment by XiaoningLiu** [comment]
@wslaghekke Validation passed. But seems the `if` code block for starting with / doesn't get test case covered. Can you add a simple test to cover this scenario?

**Comment by wslaghekke** [comment]
I've updated the PR with a test for generateCanonicalResource

**Comment by XiaoningLiu** [comment]
Thanks. Under validation.

**Pull request merged**
