### PR TITLE
Refactor assertions

### PR DESCRIPTION
**Pull request by carusogabriel**
Refactor some assertions using dedicated `PHPUnit` methods instead of PHP's.

Thanks to [`Rector`](https://github.com/rectorphp/rector) that helped me find them.

### CODE REVIEW

**Comment by katmsft** [comment]
Thanks for the PR, it looks good to me, but it's going to the wrong branch. Please resend this PR to dev branch instead.

**Comment by XiaoningLiu** [comment]
@carusogabriel @katmsft  This PR has one error during phpunit validation. Please have a look.

```
  [phpunit] There was 1 error:
  [phpunit] 
  [phpunit] 1) MicrosoftAzure\Storage\Tests\Functional\Queue\QueueServiceFunctionalOptionsTest::testCheckCreateQueueOptions
  [phpunit] PHPUnit_Framework_Exception: Argument #2 (No Value) of PHPUnit_Framework_Assert::assertCount() must be a countable or traversable
  [phpunit] 
  [phpunit] C:\Program Files (x86)\Jenkins\workspace\PHP-ft-manual\tests\Functional\Queue\QueueServiceFunctionalOptionsTest.php:148
```

**Comment by carusogabriel** [comment]
@XiaoningLiu May I ask you how did you run the tests? So I can run locally and fix them :smile:

**Comment by XiaoningLiu** [comment]
@carusogabriel Please follow https://github.com/Azure/azure-storage-php/blob/master/CONTRIBUTING.md#tests for set up your test. You need a **clean** storage account for testing.

Simply, after configuring your PHP environment:

```
composer install
set AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=https;AccountName=<Account>;AccountKey=<Key>
ant phpunit-ut
ant phpunit-ft
```

If you doesn't have ant installed, using following commands to start phpunit:
```
./vendor/bin/phpunit --configuration phpunit.xml.dist --testsuite=unit --exclude-group=large-scale
./vendor/bin/phpunit --configuration phpunit.xml.dist --testsuite=functional --exclude-group=large-scale
```

**Comment by carusogabriel** [comment]
Done :+1:

**Pull request merged**
