### PR TITLE
Removed unused imports

### PR DESCRIPTION
**Pull request by Nyholm**

### CODE REVIEW

**Comment by katmsft** [comment]
Hi @Nyholm , I am currently running your PR's validation, the change looks good to me generally. BTW, could you please share why this code change is important for you?

**Comment by Nyholm** [comment]
Hey. 
No it is not important. I just found this library and reviewed the code and found some easy fixes. To be honest, I also wanted to see your response time and if you are welcoming changes. 😄

**Comment by katmsft** [comment]
We are definitely welcoming changes as long as we are convinced that it is valid. And we do not have a officially guaranteed response time but normally we will provide actionable response within 2 working days.

**Comment by Nyholm** [comment]
Sure. I've done it now. 

FYI, you can do this for me by clicking the edit button at the top right of the PR. (Same as editing the title)

**Comment by katmsft** [comment]
@Nyholm Although I do want to do it for you, I do not have the access for this operation. I might be the main contributor for the repo for now, but I am not the owner, nor do I have write access to this repository.

Thanks for making the change BTW.

**Comment by katmsft** [comment]
@Nyholm The PR is merged. Normally we merge PRs when we are about to release. If you have any concern regarding this, or if you want some of your PRs merged ASAP, please do let us know in advance. Thanks.

**Comment by Nyholm** [comment]
Thank you for merging. 

Im in no rush. =)

**Pull request merged**
