### PR TITLE
Don't treat any empty lines as headers

### LINKED ISSUE #191: Table: batch operations fail with Header name can not be empty
### Which service(blob, file, queue, table) does this issue concern?
Table

### Which version of the SDK was used?
1.1.1, and master + dev branches

### What problem was encountered?
Batch operations fail with "Header name can not be empty" exception, because guzzle/psr7 has added an empty header check in 1.6.0 which is failing now: https://github.com/guzzle/psr7/pull/250 + https://github.com/guzzle/psr7/pull/272

### Steps to reproduce the issue?
1. Clone the repo
2. Install dependencies `composer install`
3. Run the test with e.g.

```
AZURE_STORAGE_CONNECTION_STRING="UseDevelopmentStorage=true" vendor/bin/phpunit -c phpunit.xml.dist --filter BatchResultTest
```

The test will fail with

```
There was 1 error:

1) MicrosoftAzure\Storage\Tests\Unit\Table\Models\BatchResultTest::testCreate
InvalidArgumentException: Header name can not be empty.

/media/snafu-htdocs/private/libs/azure-storage-php/vendor/guzzlehttp/psr7/src/MessageTrait.php:210
/media/snafu-htdocs/private/libs/azure-storage-php/vendor/guzzlehttp/psr7/src/MessageTrait.php:146
/media/snafu-htdocs/private/libs/azure-storage-php/vendor/guzzlehttp/psr7/src/Response.php:106
/media/snafu-htdocs/private/libs/azure-storage-php/azure-storage-table/src/Table/Models/BatchResult.php:154
/media/snafu-htdocs/private/libs/azure-storage-php/tests/Unit/Table/Models/BatchResultTest.php:57
```

### Have you found a mitigation/solution?
Yes. The issue is here

https://github.com/Azure/azure-storage-php/blob/f27c5ed72a17bed5e784469d7be4b0fd0ed4a2e1/azure-storage-table/src/Table/Models/BatchResult.php#L79-L84

The empty line which serves as a header/body delimiter in HTTP will be added to the headers array with null value before the do/while loop ends on `Resources::EMPTY_STRING != $headerLine` and then the psr7's assert will fail. I'll prepare a PR with a suggested fix (done: #192).

Do you run any sort of periodical tests/CI that would alert you to this issue as soon as possible?

### PR DESCRIPTION
**Pull request by spaze**
First check if the header line is empty, and only parse it as a header line if it's not.

Fix #191

### CODE REVIEW

**Comment by ScottHelme** [comment]
Just checking in on this, would be cool to get an update! 👍

**Comment by XiaoningLiu** [comment]
@vinjiang Please help merge.

**Comment by spaze** [comment]
Hi folks! Can we please get this merged to master and released? Thanks!

**Comment by XiaoningLiu** [comment]
Thanks @spaze ! Will check with our team about next release schedule.

**Comment by spaze** [comment]
Hi, can we please get this released? It's been a while. Thanks.

**Comment by XiaoningLiu** [comment]
Hi @spaze We are preparing for a release planned in this week.

**Comment by spaze** [comment]
Thank you for the release @XiaoningLiu & @katmsft!

**Pull request merged**
